### ISSUE TITLE
How can i use this api?

### ISSUE THREAD

**Issue by DiamondYuan** [nikuyoshi/dmm4j#1]
Do you have any documents?

**Comment by nikuyoshi** [comment]
I'm sorry, this project is on WIP.

Please use this project after finishing implementing.

**Comment by DiamondYuan** [comment]
i'm sorry ,my english is not very well.can you tell me what WIP means?
which words?

**Comment by nikuyoshi** [comment]
WIP means work in progress.
This project is not finished writing codes completely, so I  recommend not using this project, and reading the codes to you.

**Comment by DiamondYuan** [comment]
Now i  know,Thank you very much

**Comment by nikuyoshi** [comment]
See also https://github.com/nikuyoshi/dmm4j/commit/433fcf7861da316e434960df5516a041401055d9
